const $=id=>document.getElementById(id);
const SERVER=(window.KESA_SERVER_URL||'http://localhost:3210').replace(/\/+$/,'');
let token=localStorage.getItem('kesa_token')||'', mode='login', activeChat=null, chats=[], mediaRecorder=null, audioChunks=[], isRecording=false;
async function api(path,opts={}){const headers={...(opts.headers||{})};if(token)headers.Authorization='Bearer '+token;if(opts.body && !(opts.body instanceof FormData))headers['Content-Type']='application/json';const r=await fetch(SERVER+path,{...opts,headers});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.error||'Ошибка сервера ('+r.status+')');return data}
function showAuth(){ $('auth').classList.remove('hidden');$('app').classList.add('hidden')}
function showApp(user){$('auth').classList.add('hidden');$('app').classList.remove('hidden');$('myName').textContent=user.username;$('myAvatar').textContent=user.username[0].toUpperCase();loadChats()}
$('loginTab').onclick=()=>setMode('login');$('registerTab').onclick=()=>setMode('register');
function setMode(m){mode=m;$('loginTab').classList.toggle('active',m==='login');$('registerTab').classList.toggle('active',m==='register');$('authSubmit').innerHTML=m==='login'?'Войти в KESA <span>↗</span>':'Создать аккаунт <span>↗</span>';$('password').autocomplete=m==='login'?'current-password':'new-password';$('authError').textContent=''}
$('authForm').onsubmit=async e=>{e.preventDefault();$('authError').textContent='';$('authSubmit').disabled=true;try{const d=await api('/api/auth/'+mode,{method:'POST',body:JSON.stringify({username:$('username').value.trim(),password:$('password').value})});token=d.token;localStorage.setItem('kesa_token',token);showApp(d.user)}catch(err){$('authError').textContent=err.message}finally{$('authSubmit').disabled=false}};
async function loadChats(){try{const d=await api('/api/chats');chats=d.chats||[];renderChats();$('connection').textContent='● Сервер подключён';$('connection').style.color='#48e3a4'}catch(e){$('connection').textContent='● Нет соединения';$('connection').style.color='#ff8197'}}
function renderChats(){$('chatList').innerHTML='';chats.forEach(c=>{const el=document.createElement('div');el.className='chat-item'+(activeChat&&activeChat.id===c.id?' active':'');el.innerHTML='<div class="avatar"></div><div class="chat-meta"><b></b><small></small></div>';el.querySelector('.avatar').textContent=(c.title||'?')[0].toUpperCase();el.querySelector('b').textContent=c.title;el.querySelector('small').textContent=c.type==='group'?'Групповая беседа':'Личные сообщения';el.onclick=()=>openChat(c);$('chatList').append(el)})}
async function openChat(c){activeChat=c;$('welcome').classList.add('hidden');$('messages').classList.remove('hidden');$('composer').classList.remove('hidden');$('chatTitle').textContent=c.title;$('viewEyebrow').textContent=c.type==='group'?'ГРУППОВОЙ ЧАТ':'ЛИЧНЫЕ СООБЩЕНИЯ';renderChats();await loadMessages()}
async function loadMessages(){if(!activeChat)return;try{const d=await api('/api/chats/'+activeChat.id+'/messages');$('messages').innerHTML='';(d.messages||[]).forEach(renderMessage);$('messages').scrollTop=$('messages').scrollHeight}catch(e){toast(e.message)}}
function renderMessage(m){const mine=m.sender_id===window.currentUserId;const el=document.createElement('div');el.className='message'+(mine?' mine':'');const av=document.createElement('div');av.className='avatar';av.textContent=(m.username||'?')[0].toUpperCase();const body=document.createElement('div');const bubble=document.createElement('div');bubble.className='bubble';const head=document.createElement('div');head.className='msg-head';head.textContent=m.username||'Пользователь';bubble.append(head);if(m.kind==='voice'){const a=document.createElement('audio');a.controls=true;a.src=SERVER+m.file_url; a.preload='none';bubble.append(a)}else if(m.kind==='file'){const a=document.createElement('a');a.href=SERVER+m.file_url;a.textContent='↥ '+(m.file_name||'Файл');a.target='_blank';a.rel='noopener';bubble.append(a)}else{const p=document.createElement('div');p.textContent=m.content||'';bubble.append(p)}const tm=document.createElement('div');tm.className='msg-time';tm.textContent=new Date(m.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});body.append(bubble,tm);el.append(av,body);$('messages').append(el)}
async function sendMessage(content,kind='text',extra={}){if(!activeChat)return;await api('/api/chats/'+activeChat.id+'/messages',{method:'POST',body:JSON.stringify({content,kind,...extra})});await loadMessages()}
$('composer').onsubmit=async e=>{e.preventDefault();const text=$('messageInput').value.trim();if(!text)return;try{await sendMessage(text);$('messageInput').value=''}catch(err){toast(err.message)}};
$('messageInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('composer').requestSubmit()}});
$('fileInput').onchange=async e=>{const file=e.target.files[0];if(!file||!activeChat)return;const fd=new FormData();fd.append('file',file);try{const d=await api('/api/chats/'+activeChat.id+'/upload',{method:'POST',body:fd});await loadMessages()}catch(err){toast(err.message)}finally{e.target.value=''}};
$('recordBtn').onclick=async()=>{if(isRecording){finishRecording(true);return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});audioChunks=[];mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>{if(e.data.size)audioChunks.push(e.data)};mediaRecorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());if(audioChunks.length&&isRecording){const blob=new Blob(audioChunks,{type:mediaRecorder.mimeType||'audio/webm'});const fd=new FormData();fd.append('file',blob,'voice.webm');try{await api('/api/chats/'+activeChat.id+'/upload?kind=voice',{method:'POST',body:fd});await loadMessages()}catch(e){toast(e.message)}}isRecording=false;$('recording').classList.add('hidden');$('recordBtn').textContent='♫'};mediaRecorder.start();isRecording=true;$('recording').classList.remove('hidden');$('recordBtn').textContent='●'}catch(e){toast('Разреши доступ к микрофону в настройках Windows')}}
function finishRecording(send){if(!mediaRecorder)return;if(!send)isRecording=false;mediaRecorder.stop()}
$('stopRecord').onclick=()=>finishRecording(true);$('cancelRecord').onclick=()=>finishRecording(false);
$('logout').onclick=()=>{token='';localStorage.removeItem('kesa_token');activeChat=null;showAuth()};
$('refresh').onclick=()=>{loadChats();loadMessages()};setInterval(()=>{if(token){loadChats();if(activeChat)loadMessages()}},5000);
let modalMode='dm';function openModal(type){modalMode=type;$('modalTitle').textContent=type==='group'?'Создать группу':'Новый диалог';$('modalLabel').textContent=type==='group'?'Название группы':'Имя пользователя';$('modalInput').placeholder=type==='group'?'Например, Друзья':'Точное имя пользователя';$('modalError').textContent='';$('modal').classList.remove('hidden');$('modalInput').focus()}
$('newGroup').onclick=()=>openModal('group');document.querySelector('[data-view="groups"]').onclick=()=>openModal('group');document.querySelector('[data-view="direct"]').onclick=()=>{if(activeChat)openChat(activeChat)};$('closeModal').onclick=()=>$('modal').classList.add('hidden');$('modal').onclick=e=>{if(e.target===$('modal'))$('modal').classList.add('hidden')};
$('modalForm').onsubmit=async e=>{e.preventDefault();try{const d=await api(modalMode==='group'?'/api/chats/group':'/api/chats/direct',{method:'POST',body:JSON.stringify(modalMode==='group'?{title:$('modalInput').value.trim()}:{username:$('modalInput').value.trim()})});$('modal').classList.add('hidden');await loadChats();const c=chats.find(x=>x.id===d.chat.id)||d.chat;if(c)openChat(c)}catch(err){$('modalError').textContent=err.message}};
function toast(msg){$('authError').textContent=msg;setTimeout(()=>{$('authError').textContent=''},3500)}
(async()=>{if(!token)return showAuth();try{const d=await api('/api/me');window.currentUserId=d.user.id;showApp(d.user)}catch(e){token='';localStorage.removeItem('kesa_token');showAuth()}})();
// Load current user id after auth as well.
const originalShowApp=showApp;showApp=async user=>{try{const d=await api('/api/me');window.currentUserId=d.user.id}catch{}originalShowApp(user)};