const express=require('express'),cors=require('cors'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),Database=require('better-sqlite3'),multer=require('multer'),path=require('path'),fs=require('fs'),crypto=require('crypto');
const app=express(),PORT=process.env.PORT||3210,JWT_SECRET=process.env.JWT_SECRET;
if(!JWT_SECRET||JWT_SECRET.length<32){console.error('Set JWT_SECRET to a random secret of at least 32 characters.');process.exit(1)}
const DATA=process.env.DATA_DIR||path.join(__dirname,'data'),UPLOAD=path.join(DATA,'uploads');fs.mkdirSync(UPLOAD,{recursive:true});
const db=new Database(path.join(DATA,'kesa.sqlite'));db.pragma('journal_mode = WAL');db.pragma('foreign_keys = ON');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,username TEXT UNIQUE COLLATE NOCASE,password_hash TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS chats(id INTEGER PRIMARY KEY,title TEXT NOT NULL,type TEXT NOT NULL CHECK(type IN ('direct','group')),created_by INTEGER REFERENCES users(id),created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS members(chat_id INTEGER REFERENCES chats(id) ON DELETE CASCADE,user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,PRIMARY KEY(chat_id,user_id));
CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY,chat_id INTEGER REFERENCES chats(id) ON DELETE CASCADE,sender_id INTEGER REFERENCES users(id),content TEXT,kind TEXT NOT NULL DEFAULT 'text',file_name TEXT,file_path TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
app.use(cors({origin:(process.env.ALLOWED_ORIGIN||'*')}));app.use(express.json({limit:'1mb'}));
const storage=multer.diskStorage({destination:(req,file,cb)=>cb(null,UPLOAD),filename:(req,file,cb)=>cb(null,crypto.randomBytes(18).toString('hex')+path.extname(file.originalname).slice(0,12))});
const upload=multer({storage,limits:{fileSize:25*1024*1024}});
function auth(req,res,next){try{const t=(req.headers.authorization||'').replace(/^Bearer /,'');const p=jwt.verify(t,JWT_SECRET);req.user=db.prepare('SELECT id,username FROM users WHERE id=?').get(p.id);if(!req.user)return res.status(401).json({error:'Аккаунт не найден'});next()}catch{return res.status(401).json({error:'Войдите в аккаунт заново'})}}
function member(chatId,userId){return !!db.prepare('SELECT 1 FROM members WHERE chat_id=? AND user_id=?').get(chatId,userId)}
function safeChat(c,userId){return {...c,unread:0}}
app.get('/api/health',(req,res)=>res.json({ok:true,app:'KESA'}));
app.post('/api/auth/register',async(req,res)=>{try{const username=String(req.body.username||'').trim(),password=String(req.body.password||'');if(!/^[\p{L}\p{N}_-]{3,24}$/u.test(username))return res.status(400).json({error:'Имя: 3–24 символа, буквы, цифры, _ или -'});if(password.length<6||password.length>128)return res.status(400).json({error:'Пароль должен содержать 6–128 символов'});const hash=await bcrypt.hash(password,12);const info=db.prepare('INSERT INTO users(username,password_hash) VALUES(?,?)').run(username,hash);return issue(res,info.lastInsertRowid,username)}catch(e){res.status(409).json({error:e.code==='SQLITE_CONSTRAINT_UNIQUE'?'Это имя уже занято':'Не удалось создать аккаунт'})}});
app.post('/api/auth/login',async(req,res)=>{const username=String(req.body.username||'').trim(),password=String(req.body.password||'');const u=db.prepare('SELECT * FROM users WHERE username=?').get(username);if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:'Неверное имя пользователя или пароль'});issue(res,u.id,u.username)});
function issue(res,id,username){const token=jwt.sign({id},JWT_SECRET,{expiresIn:'30d'});res.json({token,user:{id,username}})}
app.get('/api/me',auth,(req,res)=>res.json({user:req.user}));
app.get('/api/chats',auth,(req,res)=>{const rows=db.prepare(`SELECT c.id,c.title,c.type,c.created_at FROM chats c JOIN members m ON m.chat_id=c.id WHERE m.user_id=? ORDER BY c.id DESC`).all(req.user.id).map(c=>{if(c.type==='direct'){const other=db.prepare('SELECT u.username FROM members m JOIN users u ON u.id=m.user_id WHERE m.chat_id=? AND u.id<>?').get(c.id,req.user.id);c.title=other?other.username:'Личный чат'}return safeChat(c,req.user.id)});res.json({chats:rows})});
app.post('/api/chats/direct',auth,(req,res)=>{const name=String(req.body.username||'').trim();const other=db.prepare('SELECT id,username FROM users WHERE username=?').get(name);if(!other)return res.status(404).json({error:'Пользователь не найден — он должен сначала зарегистрироваться'});if(other.id===req.user.id)return res.status(400).json({error:'Нельзя создать чат с самим собой'});let chat=db.prepare(`SELECT c.id,c.title,c.type FROM chats c JOIN members a ON a.chat_id=c.id AND a.user_id=? JOIN members b ON b.chat_id=c.id AND b.user_id=? WHERE c.type='direct' LIMIT 1`).get(req.user.id,other.id);if(!chat){const create=db.transaction(()=>{const r=db.prepare("INSERT INTO chats(title,type,created_by) VALUES(?,'direct',?)").run(other.username,req.user.id);db.prepare('INSERT INTO members(chat_id,user_id) VALUES(?,?)').run(r.lastInsertRowid,req.user.id);db.prepare('INSERT INTO members(chat_id,user_id) VALUES(?,?)').run(r.lastInsertRowid,other.id);return {id:r.lastInsertRowid,title:other.username,type:'direct'}});chat=create()}res.json({chat})});
app.post('/api/chats/group',auth,(req,res)=>{const title=String(req.body.title||'').trim();if(title.length<2||title.length>60)return res.status(400).json({error:'Название группы: 2–60 символов'});const tx=db.transaction(()=>{const r=db.prepare("INSERT INTO chats(title,type,created_by) VALUES(?,'group',?)").run(title,req.user.id);db.prepare('INSERT INTO members(chat_id,user_id) VALUES(?,?)').run(r.lastInsertRowid,req.user.id);return {id:r.lastInsertRowid,title,type:'group'}});res.json({chat:tx()})});
app.get('/api/chats/:id/messages',auth,(req,res)=>{const id=Number(req.params.id);if(!member(id,req.user.id))return res.status(403).json({error:'Нет доступа к этому чату'});const messages=db.prepare(`SELECT m.id,m.chat_id,m.sender_id,u.username,m.content,m.kind,m.file_name,m.file_path,m.created_at FROM messages m JOIN users u ON u.id=m.sender_id WHERE m.chat_id=? ORDER BY m.id DESC LIMIT 150`).all(id).reverse().map(m=>({...m,file_url:m.file_path?'/api/files/'+path.basename(m.file_path):null}));res.json({messages})});
app.post('/api/chats/:id/messages',auth,(req,res)=>{const id=Number(req.params.id);if(!member(id,req.user.id))return res.status(403).json({error:'Нет доступа к этому чату'});const content=String(req.body.content||'').trim();if(!content||content.length>4000)return res.status(400).json({error:'Сообщение пустое или слишком длинное'});const r=db.prepare("INSERT INTO messages(chat_id,sender_id,content,kind) VALUES(?,?,?,'text')").run(id,req.user.id,content);res.json({id:r.lastInsertRowid,ok:true})});
app.post('/api/chats/:id/upload',auth,(req,res)=>{const id=Number(req.params.id);if(!member(id,req.user.id))return res.status(403).json({error:'Нет доступа к этому чату'});upload.single('file')(req,res,err=>{if(err)return res.status(400).json({error:err.code==='LIMIT_FILE_SIZE'?'Максимальный размер файла — 25 МБ':'Не удалось загрузить файл'});if(!req.file)return res.status(400).json({error:'Файл не выбран'});const voice=req.query.kind==='voice'||req.file.originalname==='voice.webm';const r=db.prepare('INSERT INTO messages(chat_id,sender_id,content,kind,file_name,file_path) VALUES(?,?,?,?,?,?)').run(id,req.user.id,'',voice?'voice':'file',path.basename(req.file.originalname).slice(0,180),req.file.filename);res.json({ok:true,id:r.lastInsertRowid})})});
app.get('/api/files/:name',auth,(req,res)=>{const row=db.prepare('SELECT m.file_path,m.file_name,m.chat_id FROM messages m WHERE m.file_path=?').get(req.params.name);if(!row||!member(row.chat_id,req.user.id))return res.status(404).json({error:'Файл не найден'});res.download(path.join(UPLOAD,path.basename(row.file_path)),row.file_name)});
app.listen(PORT,'0.0.0.0',()=>console.log(`KESA server listening on ${PORT}`));