const express=require('express'),cors=require('cors'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),Database=require('better-sqlite3'),multer=require('multer'),path=require('path'),fs=require('fs'),crypto=require('crypto');
const app=express(),PORT=process.env.PORT||3210,JWT_SECRET=process.env.JWT_SECRET;
if(!JWT_SECRET||JWT_SECRET.length<32){console.error('Set JWT_SECRET to a random secret of at least 32 characters.');process.exit(1)}
const DATA=process.env.DATA_DIR||path.join(__dirname,'data'),UPLOAD=path.join(DATA,'uploads');fs.mkdirSync(UPLOAD,{recursive:true});
const db=new Database(path.join(DATA,'kesa.sqlite'));db.pragma('journal_mode = WAL');db.pragma('foreign_keys = ON');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,username TEXT UNIQUE COLLATE NOCASE,password_hash TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS chats(id INTEGER PRIMARY KEY,title TEXT NOT NULL,type TEXT NOT NULL CHECK(type IN ('direct','group')),created_by INTEGER REFERENCES users(id),created_at TEXT DEFAULT CURRENT_TIMESTAMP, is_channel INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS members(chat_id INTEGER REFERENCES chats(id) ON DELETE CASCADE,user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,role TEXT NOT NULL DEFAULT 'member',muted_until TEXT,PRIMARY KEY(chat_id,user_id));
CREATE TABLE IF NOT EXISTS chat_bans(chat_id INTEGER REFERENCES chats(id) ON DELETE CASCADE,user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,by_user INTEGER REFERENCES users(id),reason TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(chat_id,user_id));
CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY,chat_id INTEGER REFERENCES chats(id) ON DELETE CASCADE,sender_id INTEGER REFERENCES users(id),content TEXT,kind TEXT NOT NULL DEFAULT 'text',file_name TEXT,file_path TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS friend_requests(id INTEGER PRIMARY KEY,from_id INTEGER REFERENCES users(id) ON DELETE CASCADE,to_id INTEGER REFERENCES users(id) ON DELETE CASCADE,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(from_id,to_id));
CREATE TABLE IF NOT EXISTS friends(user1 INTEGER REFERENCES users(id) ON DELETE CASCADE,user2 INTEGER REFERENCES users(id) ON DELETE CASCADE,created_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(user1,user2));
CREATE TABLE IF NOT EXISTS call_signals(id INTEGER PRIMARY KEY,from_id INTEGER REFERENCES users(id) ON DELETE CASCADE,to_id INTEGER REFERENCES users(id) ON DELETE CASCADE,call_id TEXT NOT NULL,type TEXT NOT NULL,payload TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS call_rooms(id TEXT PRIMARY KEY,chat_id INTEGER NOT NULL REFERENCES chats(id) ON DELETE CASCADE,host_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,mode TEXT NOT NULL DEFAULT 'audio',status TEXT NOT NULL DEFAULT 'active',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS call_room_members(room_id TEXT NOT NULL REFERENCES call_rooms(id) ON DELETE CASCADE,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,joined_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(room_id,user_id));
`);
for(const [name,def] of [['bio',"TEXT NOT NULL DEFAULT ''"],['avatar_path','TEXT'],['cover_path','TEXT']]){try{db.exec(`ALTER TABLE users ADD COLUMN ${name} ${def}`)}catch(e){if(!String(e.message).includes('duplicate column'))throw e}}
for(const [table,name,def] of [['chats','is_channel','INTEGER NOT NULL DEFAULT 0'],['members','role',"TEXT NOT NULL DEFAULT 'member'"],['members','muted_until','TEXT']]){try{db.exec(`ALTER TABLE ${table} ADD COLUMN ${name} ${def}`)}catch(e){if(!String(e.message).includes('duplicate column'))throw e}}
// Backfill creator roles for existing group chats.
db.exec("UPDATE members SET role='owner' WHERE EXISTS (SELECT 1 FROM chats c WHERE c.id=members.chat_id AND c.created_by=members.user_id AND c.type='group')");
app.use(cors({origin:process.env.ALLOWED_ORIGIN||'*'}));app.use(express.json({limit:'2mb'}));
const storage=multer.diskStorage({destination:(req,file,cb)=>cb(null,UPLOAD),filename:(req,file,cb)=>cb(null,crypto.randomBytes(18).toString('hex')+path.extname(file.originalname).slice(0,12).toLowerCase())});
const upload=multer({storage,limits:{fileSize:8*1024*1024},fileFilter:(req,file,cb)=>{const ok=/^(image\/(png|jpeg|webp|gif)|audio\/(webm|ogg|mpeg|mp4)|video\/(webm|mp4)|application\/pdf|text\/plain|application\/zip)$/.test(file.mimetype)||file.originalname==='voice.webm';cb(ok?null:new Error('Этот тип файла не поддерживается'),ok)}});
function auth(req,res,next){try{const t=(req.headers.authorization||'').replace(/^Bearer /,'');const p=jwt.verify(t,JWT_SECRET);req.user=db.prepare('SELECT id,username,bio,avatar_path,cover_path FROM users WHERE id=?').get(p.id);if(!req.user)return res.status(401).json({error:'Аккаунт не найден'});next()}catch{return res.status(401).json({error:'Войдите в аккаунт заново'})}}
function member(chatId,userId){return !!db.prepare('SELECT 1 FROM members WHERE chat_id=? AND user_id=?').get(chatId,userId)&&!db.prepare('SELECT 1 FROM chat_bans WHERE chat_id=? AND user_id=?').get(chatId,userId)}
function chatRole(chatId,userId){return db.prepare('SELECT role FROM members WHERE chat_id=? AND user_id=?').get(chatId,userId)?.role||null}
function getManageableChat(chatId,userId){return db.prepare("SELECT * FROM chats WHERE id=? AND type='group'").get(chatId)}
function canModerate(chatId,userId){return ['owner','admin','moderator'].includes(chatRole(chatId,userId))}
function requireChatRole(req,res,minimum='admin'){const c=getManageableChat(Number(req.params.id),req.user.id);if(!c)return (res.status(404).json({error:'Чат или канал не найден'}),null);const role=chatRole(c.id,req.user.id);const allowed=minimum==='owner'?role==='owner':minimum==='moderator'?['owner','admin','moderator'].includes(role):['owner','admin'].includes(role);if(!allowed){res.status(403).json({error:'Недостаточно прав для этого действия'});return null}return c}
function publicUser(u){return {id:u.id,username:u.username,bio:u.bio||'',avatar_url:u.avatar_path?'/api/media/'+path.basename(u.avatar_path):null,cover_url:u.cover_path?'/api/media/'+path.basename(u.cover_path):null,created_at:u.created_at}}
function fileUrl(row){return row?'/api/media/'+path.basename(row):null}
function chatForUser(id,uid){return db.prepare(`SELECT c.id,c.type FROM chats c JOIN members m ON m.chat_id=c.id WHERE c.id=? AND m.user_id=?`).get(id,uid)}
function peerInChat(id,uid){return db.prepare(`SELECT u.id,u.username FROM members m JOIN users u ON u.id=m.user_id WHERE m.chat_id=? AND u.id<>? LIMIT 1`).get(id,uid)}
function sendIssue(res,id,username){res.json({token:jwt.sign({id},JWT_SECRET,{expiresIn:'30d'}),user:{id,username}})}
app.get('/',(req,res)=>res.json({ok:true,app:'KESA Messenger API',health:'/api/health'}));
app.get('/api/health',(req,res)=>res.json({ok:true,app:'KESA',features:['profiles','friends','voice','webrtc-signaling','group-calls','themes','channels','chat-roles','moderation','ownership-transfer']}));
app.post('/api/auth/register',async(req,res)=>{try{const username=String(req.body.username||'').trim(),password=String(req.body.password||'');if(!/^[\p{L}\p{N}_-]{3,24}$/u.test(username))return res.status(400).json({error:'Имя: 3–24 символа, буквы, цифры, _ или -'});if(password.length<6||password.length>128)return res.status(400).json({error:'Пароль должен содержать 6–128 символов'});const hash=await bcrypt.hash(password,12);const info=db.prepare('INSERT INTO users(username,password_hash) VALUES(?,?)').run(username,hash);sendIssue(res,info.lastInsertRowid,username)}catch(e){res.status(409).json({error:e.code==='SQLITE_CONSTRAINT_UNIQUE'?'Это имя уже занято':'Не удалось создать аккаунт'})}});
app.post('/api/auth/login',async(req,res)=>{const username=String(req.body.username||'').trim(),password=String(req.body.password||'');const u=db.prepare('SELECT * FROM users WHERE username=?').get(username);if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:'Неверное имя пользователя или пароль'});sendIssue(res,u.id,u.username)});
app.get('/api/me',auth,(req,res)=>res.json({user:publicUser(db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id))}));
app.put('/api/profile',auth,(req,res)=>{const bio=String(req.body.bio||'').trim().slice(0,300);db.prepare('UPDATE users SET bio=? WHERE id=?').run(bio,req.user.id);res.json({ok:true,user:publicUser(db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id))})});
app.post('/api/profile/:kind',auth,(req,res)=>{if(!['avatar','cover'].includes(req.params.kind))return res.status(400).json({error:'Неизвестный тип изображения'});const imageUpload=multer({storage,limits:{fileSize:5*1024*1024},fileFilter:(rq,file,cb)=>cb(/^image\/(png|jpeg|webp|gif)$/.test(file.mimetype)?null:new Error('Нужна картинка PNG, JPG, WEBP или GIF'),/^image\/(png|jpeg|webp|gif)$/.test(file.mimetype))}).single('file');imageUpload(req,res,err=>{if(err)return res.status(400).json({error:err.code==='LIMIT_FILE_SIZE'?'Изображение максимум 5 МБ':err.message||'Ошибка загрузки'});if(!req.file)return res.status(400).json({error:'Выбери изображение'});const col=req.params.kind==='avatar'?'avatar_path':'cover_path';db.prepare(`UPDATE users SET ${col}=? WHERE id=?`).run(req.file.filename,req.user.id);res.json({ok:true,user:publicUser(db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id))})})});
app.get('/api/users/search',auth,(req,res)=>{const q=String(req.query.q||'').trim().slice(0,24);if(q.length<2)return res.json({users:[]});const rows=db.prepare(`SELECT u.id,u.username,u.bio,u.avatar_path,u.cover_path,u.created_at,CASE WHEN EXISTS(SELECT 1 FROM friends f WHERE f.user1=MIN(u.id,?) AND f.user2=MAX(u.id,?)) THEN 'friend' WHEN EXISTS(SELECT 1 FROM friend_requests r WHERE r.from_id=? AND r.to_id=u.id AND r.status='pending') THEN 'sent' WHEN EXISTS(SELECT 1 FROM friend_requests r WHERE r.from_id=u.id AND r.to_id=? AND r.status='pending') THEN 'received' ELSE 'none' END AS friendship_state,(SELECT id FROM friend_requests r WHERE r.from_id=? AND r.to_id=u.id AND r.status='pending' LIMIT 1) AS outgoing_request_id,(SELECT id FROM friend_requests r WHERE r.from_id=u.id AND r.to_id=? AND r.status='pending' LIMIT 1) AS incoming_request_id FROM users u WHERE u.id<>? AND instr(lower(u.username),lower(?))>0 ORDER BY u.username LIMIT 25`).all(req.user.id,req.user.id,req.user.id,req.user.id,req.user.id,req.user.id,req.user.id,q);res.json({users:rows.map(u=>({...publicUser(u),friendship_state:u.friendship_state,outgoing_request_id:u.outgoing_request_id,incoming_request_id:u.incoming_request_id}))})});
app.get('/api/friends',auth,(req,res)=>{const users=db.prepare(`SELECT u.* FROM friends f JOIN users u ON u.id=CASE WHEN f.user1=? THEN f.user2 ELSE f.user1 END WHERE f.user1=? OR f.user2=? ORDER BY u.username`).all(req.user.id,req.user.id,req.user.id).map(publicUser);const incoming=db.prepare(`SELECT r.id,r.created_at,u.id AS user_id,u.username,u.bio,u.avatar_path,u.cover_path FROM friend_requests r JOIN users u ON u.id=r.from_id WHERE r.to_id=? AND r.status='pending' ORDER BY r.id DESC`).all(req.user.id).map(r=>({request_id:r.id,user:publicUser({id:r.user_id,username:r.username,bio:r.bio,avatar_path:r.avatar_path,cover_path:r.cover_path,created_at:r.created_at})}));res.json({friends:users,incoming})});
app.post('/api/friends/request',auth,(req,res)=>{const id=Number(req.body.user_id);if(!id||id===req.user.id)return res.status(400).json({error:'Выбери другого пользователя'});if(!db.prepare('SELECT id FROM users WHERE id=?').get(id))return res.status(404).json({error:'Пользователь не найден'});const a=Math.min(id,req.user.id),b=Math.max(id,req.user.id);if(db.prepare('SELECT 1 FROM friends WHERE user1=? AND user2=?').get(a,b))return res.status(400).json({error:'Вы уже друзья'});const reverse=db.prepare("SELECT id FROM friend_requests WHERE from_id=? AND to_id=? AND status='pending'").get(id,req.user.id);if(reverse){const tx=db.transaction(()=>{db.prepare("UPDATE friend_requests SET status='accepted' WHERE id=?").run(reverse.id);db.prepare('INSERT OR IGNORE INTO friends(user1,user2) VALUES(?,?)').run(a,b)});tx();return res.json({ok:true,accepted:true})}const previous=db.prepare('SELECT id,status FROM friend_requests WHERE from_id=? AND to_id=?').get(req.user.id,id);if(previous?.status==='pending')return res.status(409).json({error:'Заявка уже отправлена'});if(previous){db.prepare("UPDATE friend_requests SET status='pending',created_at=CURRENT_TIMESTAMP WHERE id=?").run(previous.id)}else{db.prepare("INSERT INTO friend_requests(from_id,to_id,status) VALUES(?,?,'pending')").run(req.user.id,id)}res.json({ok:true})});
app.post('/api/friends/:requestId/accept',auth,(req,res)=>{const id=Number(req.params.requestId),r=db.prepare("SELECT * FROM friend_requests WHERE id=? AND to_id=? AND status='pending'").get(id,req.user.id);if(!r)return res.status(404).json({error:'Заявка не найдена'});const a=Math.min(r.from_id,r.to_id),b=Math.max(r.from_id,r.to_id);const tx=db.transaction(()=>{db.prepare("UPDATE friend_requests SET status='accepted' WHERE id=?").run(id);db.prepare('INSERT OR IGNORE INTO friends(user1,user2) VALUES(?,?)').run(a,b)});tx();res.json({ok:true})});
app.post('/api/friends/:requestId/decline',auth,(req,res)=>{db.prepare("UPDATE friend_requests SET status='declined' WHERE id=? AND to_id=? AND status='pending'").run(Number(req.params.requestId),req.user.id);res.json({ok:true})});
app.get('/api/chats',auth,(req,res)=>{const rows=db.prepare(`SELECT c.id,c.title,c.type,c.is_channel,c.created_at,m.role FROM chats c JOIN members m ON m.chat_id=c.id WHERE m.user_id=? ORDER BY c.id DESC`).all(req.user.id).map(c=>{if(c.type==='direct'){const other=peerInChat(c.id,req.user.id);c.title=other?other.username:'Личный чат';c.peer_id=other?.id||null;c.peer_avatar=other?fileUrl(db.prepare('SELECT avatar_path FROM users WHERE id=?').get(other.id)?.avatar_path):null}return {...c,unread:0}});res.json({chats:rows})});
app.post('/api/chats/direct',auth,(req,res)=>{const name=String(req.body.username||'').trim();const other=db.prepare('SELECT id,username FROM users WHERE username=?').get(name);if(!other)return res.status(404).json({error:'Пользователь не найден — он должен сначала зарегистрироваться'});if(other.id===req.user.id)return res.status(400).json({error:'Нельзя создать чат с самим собой'});let chat=db.prepare(`SELECT c.id,c.title,c.type FROM chats c JOIN members a ON a.chat_id=c.id AND a.user_id=? JOIN members b ON b.chat_id=c.id AND b.user_id=? WHERE c.type='direct' LIMIT 1`).get(req.user.id,other.id);if(!chat){const create=db.transaction(()=>{const r=db.prepare("INSERT INTO chats(title,type,created_by) VALUES(?,'direct',?)").run(other.username,req.user.id);db.prepare('INSERT INTO members(chat_id,user_id) VALUES(?,?)').run(r.lastInsertRowid,req.user.id);db.prepare('INSERT INTO members(chat_id,user_id) VALUES(?,?)').run(r.lastInsertRowid,other.id);return {id:r.lastInsertRowid,title:other.username,type:'direct',peer_id:other.id}});chat=create()}res.json({chat})});
app.post('/api/chats/group',auth,(req,res)=>{const title=String(req.body.title||'').trim();if(title.length<2||title.length>60)return res.status(400).json({error:'Название группы: 2–60 символов'});const tx=db.transaction(()=>{const r=db.prepare("INSERT INTO chats(title,type,created_by) VALUES(?,'group',?)").run(title,req.user.id);db.prepare("INSERT INTO members(chat_id,user_id,role) VALUES(?,?,'owner')").run(r.lastInsertRowid,req.user.id);return {id:r.lastInsertRowid,title,type:'group',is_channel:0,role:'owner'}});res.json({chat:tx()})});
app.post('/api/chats/channel',auth,(req,res)=>{const title=String(req.body.title||'').trim();if(title.length<2||title.length>60)return res.status(400).json({error:'Название канала: 2–60 символов'});const tx=db.transaction(()=>{const r=db.prepare("INSERT INTO chats(title,type,created_by,is_channel) VALUES(?,'group',?,1)").run(title,req.user.id);db.prepare("INSERT INTO members(chat_id,user_id,role) VALUES(?,?,'owner')").run(r.lastInsertRowid,req.user.id);return {id:r.lastInsertRowid,title,type:'group',is_channel:1,role:'owner'}});res.json({chat:tx()})});
app.get('/api/chats/:id/manage',auth,(req,res)=>{const id=Number(req.params.id),c=getManageableChat(id,req.user.id);if(!c||!member(id,req.user.id))return res.status(404).json({error:'Чат или канал не найден'});const role=chatRole(id,req.user.id);const users=db.prepare(`SELECT u.id,u.username,m.role,m.muted_until FROM members m JOIN users u ON u.id=m.user_id WHERE m.chat_id=? ORDER BY CASE m.role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 WHEN 'moderator' THEN 2 ELSE 3 END,u.username`).all(id);res.json({chat:{id:c.id,title:c.title,is_channel:!!c.is_channel,created_by:c.created_by},role,members:users,can_manage:['owner','admin','moderator'].includes(role),is_owner:role==='owner'})});
app.post('/api/chats/:id/members',auth,(req,res)=>{const id=Number(req.params.id),userId=Number(req.body.user_id),c=getManageableChat(id,req.user.id);if(!c||!member(id,req.user.id))return res.status(404).json({error:'Чат или канал не найден'});if(!canModerate(id,req.user.id))return res.status(403).json({error:'Добавлять участников может администратор'});const u=db.prepare('SELECT id FROM users WHERE id=?').get(userId);if(!u)return res.status(404).json({error:'Пользователь не найден'});if(db.prepare('SELECT 1 FROM chat_bans WHERE chat_id=? AND user_id=?').get(id,userId))return res.status(403).json({error:'Этот пользователь заблокирован в чате'});db.prepare("INSERT OR IGNORE INTO members(chat_id,user_id,role) VALUES(?,?,'member')").run(id,userId);res.json({ok:true})});
app.post('/api/chats/:id/transfer',auth,(req,res)=>{const c=requireChatRole(req,res,'owner');if(!c)return;const target=Number(req.body.user_id);if(!member(c.id,target))return res.status(400).json({error:'Передать владение можно только участнику чата'});if(target===req.user.id)return res.status(400).json({error:'Ты уже создатель'});const tx=db.transaction(()=>{db.prepare("UPDATE members SET role='admin' WHERE chat_id=? AND user_id=?").run(c.id,req.user.id);db.prepare("UPDATE members SET role='owner' WHERE chat_id=? AND user_id=?").run(c.id,target);db.prepare('UPDATE chats SET created_by=? WHERE id=?').run(target,c.id)});tx();res.json({ok:true,message:'Права создателя переданы'})});
app.post('/api/chats/:id/role',auth,(req,res)=>{const c=requireChatRole(req,res,'owner');if(!c)return;const target=Number(req.body.user_id),role=String(req.body.role||'member');if(!['admin','moderator','member'].includes(role))return res.status(400).json({error:'Неизвестная роль'});if(!member(c.id,target))return res.status(404).json({error:'Участник не найден'});if(target===req.user.id||chatRole(c.id,target)==='owner')return res.status(400).json({error:'Нельзя изменить роль создателя'});db.prepare('UPDATE members SET role=? WHERE chat_id=? AND user_id=?').run(role,c.id,target);res.json({ok:true})});
app.post('/api/chats/:id/mute',auth,(req,res)=>{const c=requireChatRole(req,res,'moderator');if(!c)return;const target=Number(req.body.user_id),minutes=Math.max(0,Math.min(10080,Number(req.body.minutes)||0));if(!member(c.id,target))return res.status(404).json({error:'Участник не найден'});const targetRole=chatRole(c.id,target),myRole=chatRole(c.id,req.user.id);if(target===req.user.id||targetRole==='owner'||(myRole!=='owner'&&targetRole==='admin'))return res.status(403).json({error:'Нельзя применить мут к этому участнику'});db.prepare('UPDATE members SET muted_until=? WHERE chat_id=? AND user_id=?').run(minutes?new Date(Date.now()+minutes*60000).toISOString():null,c.id,target);res.json({ok:true,message:minutes?'Мут установлен':'Мут снят'})});
app.post('/api/chats/:id/ban',auth,(req,res)=>{const c=requireChatRole(req,res,'moderator');if(!c)return;const target=Number(req.body.user_id),reason=String(req.body.reason||'').trim().slice(0,200);if(!member(c.id,target))return res.status(404).json({error:'Участник не найден'});const targetRole=chatRole(c.id,target),myRole=chatRole(c.id,req.user.id);if(target===req.user.id||targetRole==='owner'||(myRole!=='owner'&&targetRole==='admin'))return res.status(403).json({error:'Нельзя заблокировать этого участника'});const tx=db.transaction(()=>{db.prepare('INSERT OR REPLACE INTO chat_bans(chat_id,user_id,by_user,reason) VALUES(?,?,?,?)').run(c.id,target,req.user.id,reason);db.prepare('DELETE FROM members WHERE chat_id=? AND user_id=?').run(c.id,target)});tx();res.json({ok:true})});
app.post('/api/chats/:id/unban',auth,(req,res)=>{const c=requireChatRole(req,res,'admin');if(!c)return;db.prepare('DELETE FROM chat_bans WHERE chat_id=? AND user_id=?').run(c.id,Number(req.body.user_id));res.json({ok:true})});
app.delete('/api/chats/:id',auth,(req,res)=>{const c=requireChatRole(req,res,'owner');if(!c)return;db.prepare('DELETE FROM chats WHERE id=?').run(c.id);res.json({ok:true})});
app.post('/api/chats/:id/leave',auth,(req,res)=>{const id=Number(req.params.id);if(!member(id,req.user.id))return res.status(404).json({error:'Чат не найден'});if(chatRole(id,req.user.id)==='owner')return res.status(400).json({error:'Передай права создателя перед выходом'});db.prepare('DELETE FROM members WHERE chat_id=? AND user_id=?').run(id,req.user.id);res.json({ok:true})});
app.get('/api/chats/:id/messages',auth,(req,res)=>{const id=Number(req.params.id);if(!member(id,req.user.id))return res.status(403).json({error:'Нет доступа к этому чату'});const rows=db.prepare(`SELECT m.id,m.chat_id,m.sender_id,u.username,u.avatar_path,m.content,m.kind,m.file_name,m.file_path,m.created_at FROM messages m JOIN users u ON u.id=m.sender_id WHERE m.chat_id=? ORDER BY m.id DESC LIMIT 150`).all(id).reverse().map(m=>({...m,avatar_url:fileUrl(m.avatar_path),file_url:m.file_path?'/api/media/'+path.basename(m.file_path):null}));res.json({messages:rows})});
app.post('/api/chats/:id/messages',auth,(req,res)=>{const id=Number(req.params.id);if(!member(id,req.user.id))return res.status(403).json({error:'Нет доступа к этому чату'});const muted=db.prepare('SELECT muted_until FROM members WHERE chat_id=? AND user_id=?').get(id,req.user.id)?.muted_until;if(muted&&Date.parse(muted)>Date.now())return res.status(403).json({error:'У тебя мут до '+new Date(muted).toLocaleString('ru-RU')});const content=String(req.body.content||'').trim();if(!content||content.length>4000)return res.status(400).json({error:'Сообщение пустое или слишком длинное'});const r=db.prepare("INSERT INTO messages(chat_id,sender_id,content,kind) VALUES(?,?,?,'text')").run(id,req.user.id,content);res.json({id:r.lastInsertRowid,ok:true})});
app.post('/api/chats/:id/upload',auth,(req,res)=>{const id=Number(req.params.id);if(!member(id,req.user.id))return res.status(403).json({error:'Нет доступа к этому чату'});const muted=db.prepare('SELECT muted_until FROM members WHERE chat_id=? AND user_id=?').get(id,req.user.id)?.muted_until;if(muted&&Date.parse(muted)>Date.now())return res.status(403).json({error:'У тебя мут в этом чате'});upload.single('file')(req,res,err=>{if(err)return res.status(400).json({error:err.code==='LIMIT_FILE_SIZE'?'Максимальный размер файла — 8 МБ':err.message||'Не удалось загрузить файл'});if(!req.file)return res.status(400).json({error:'Файл не выбран'});const voice=req.query.kind==='voice'||req.file.originalname==='voice.webm';const r=db.prepare('INSERT INTO messages(chat_id,sender_id,content,kind,file_name,file_path) VALUES(?,?,?,?,?,?)').run(id,req.user.id,'',voice?'voice':'file',path.basename(req.file.originalname).slice(0,180),req.file.filename);res.json({ok:true,id:r.lastInsertRowid})})});
function mediaAuth(req,res,next){if(!req.headers.authorization&&req.query.token)req.headers.authorization='Bearer '+String(req.query.token);auth(req,res,next)}
app.get('/api/media/:name',mediaAuth,(req,res)=>{const name=path.basename(req.params.name);const profile=db.prepare('SELECT id FROM users WHERE avatar_path=? OR cover_path=?').get(name,name);const msg=db.prepare('SELECT m.file_path,m.file_name,m.chat_id FROM messages m WHERE m.file_path=?').get(name);if(!profile&&(!msg||!member(msg.chat_id,req.user.id)))return res.status(404).json({error:'Файл не найден'});const fp=path.join(UPLOAD,name);if(!fs.existsSync(fp))return res.status(404).json({error:'Файл отсутствует на сервере'});if(msg)res.setHeader('Content-Disposition',`inline; filename*=UTF-8''${encodeURIComponent(msg.file_name||name)}`);res.sendFile(fp)});
app.get('/api/chats/:id/call-room',auth,(req,res)=>{const chatId=Number(req.params.id);if(!member(chatId,req.user.id))return res.status(403).json({error:'Нет доступа к этому чату'});db.prepare("UPDATE call_rooms SET status='ended' WHERE status='active' AND created_at < datetime('now','-12 hours')").run();const room=db.prepare("SELECT r.id,r.chat_id,r.host_id,r.mode,r.status,r.created_at,u.username AS host_name FROM call_rooms r JOIN users u ON u.id=r.host_id WHERE r.chat_id=? AND r.status='active' ORDER BY r.created_at DESC LIMIT 1").get(chatId);if(!room)return res.json({room:null});const members=db.prepare('SELECT u.id,u.username FROM call_room_members m JOIN users u ON u.id=m.user_id WHERE m.room_id=? ORDER BY m.joined_at').all(room.id);res.json({room,members})});
app.post('/api/chats/:id/call-room',auth,(req,res)=>{const chatId=Number(req.params.id),mode=String(req.body.mode||'audio');if(!member(chatId,req.user.id))return res.status(403).json({error:'Нет доступа к этому чату'});if(!['audio','video'].includes(mode))return res.status(400).json({error:'Неверный режим звонка'});const chat=db.prepare("SELECT * FROM chats WHERE id=? AND type='group'").get(chatId);if(!chat)return res.status(400).json({error:'Групповые звонки доступны только в группах и каналах'});db.prepare("UPDATE call_rooms SET status='ended' WHERE status='active' AND created_at < datetime('now','-12 hours')").run();let room=db.prepare("SELECT id,chat_id,host_id,mode,status,created_at FROM call_rooms WHERE chat_id=? AND status='active' ORDER BY created_at DESC LIMIT 1").get(chatId);if(room){const host=db.prepare('SELECT username FROM users WHERE id=?').get(room.host_id);const members=db.prepare('SELECT u.id,u.username FROM call_room_members m JOIN users u ON u.id=m.user_id WHERE m.room_id=?').all(room.id);return res.json({room:{...room,host_name:host?.username||'Пользователь'},members,existing:true})}const id=crypto.randomUUID();const tx=db.transaction(()=>{db.prepare("INSERT INTO call_rooms(id,chat_id,host_id,mode,status) VALUES(?,?,?,?,'active')").run(id,chatId,req.user.id,mode);db.prepare('INSERT INTO call_room_members(room_id,user_id) VALUES(?,?)').run(id,req.user.id)});tx();room=db.prepare('SELECT id,chat_id,host_id,mode,status,created_at FROM call_rooms WHERE id=?').get(id);const host=db.prepare('SELECT username FROM users WHERE id=?').get(req.user.id);const users=db.prepare('SELECT u.id,u.username FROM members m JOIN users u ON u.id=m.user_id WHERE m.chat_id=? AND u.id<>?').all(chatId,req.user.id);for(const u of users){db.prepare('INSERT INTO call_signals(from_id,to_id,call_id,type,payload) VALUES(?,?,?, ?,?)').run(req.user.id,u.id,id,'g-invite',JSON.stringify({room_id:id,chat_id:chatId,title:chat.title,mode,host_name:host.username}))}res.json({room:{...room,host_name:host.username},members:[{id:req.user.id,username:host.username}],existing:false})});
app.post('/api/call-rooms/:roomId/join',auth,(req,res)=>{const roomId=String(req.params.roomId||''),room=db.prepare("SELECT r.*,c.title FROM call_rooms r JOIN chats c ON c.id=r.chat_id WHERE r.id=? AND r.status='active'").get(roomId);if(!room)return res.status(404).json({error:'Групповой звонок уже завершён'});if(!member(room.chat_id,req.user.id))return res.status(403).json({error:'Ты не участник этой группы'});const existing=db.prepare('SELECT 1 FROM call_room_members WHERE room_id=? AND user_id=?').get(roomId,req.user.id);const others=db.prepare('SELECT u.id,u.username FROM call_room_members m JOIN users u ON u.id=m.user_id WHERE m.room_id=? AND m.user_id<>?').all(roomId,req.user.id);db.prepare('INSERT OR IGNORE INTO call_room_members(room_id,user_id) VALUES(?,?)').run(roomId,req.user.id);const me=db.prepare('SELECT username FROM users WHERE id=?').get(req.user.id);{const payload=JSON.stringify({room_id:roomId,username:me.username});for(const peer of others)db.prepare('INSERT INTO call_signals(from_id,to_id,call_id,type,payload) VALUES(?,?,?,?,?)').run(req.user.id,peer.id,roomId,'g-peer-join',payload)}res.json({ok:true,room:{id:room.id,chat_id:room.chat_id,host_id:room.host_id,mode:room.mode,title:room.title,host_name:db.prepare('SELECT username FROM users WHERE id=?').get(room.host_id)?.username||'Пользователь'},members:others})});
app.post('/api/call-rooms/:roomId/leave',auth,(req,res)=>{const roomId=String(req.params.roomId||''),room=db.prepare("SELECT * FROM call_rooms WHERE id=? AND status='active'").get(roomId);if(!room)return res.json({ok:true,ended:true});if(!db.prepare('SELECT 1 FROM call_room_members WHERE room_id=? AND user_id=?').get(roomId,req.user.id))return res.json({ok:true});const peers=db.prepare('SELECT user_id FROM call_room_members WHERE room_id=? AND user_id<>?').all(roomId,req.user.id);if(room.host_id===req.user.id){db.prepare("UPDATE call_rooms SET status='ended' WHERE id=?").run(roomId);for(const p of peers)db.prepare('INSERT INTO call_signals(from_id,to_id,call_id,type,payload) VALUES(?,?,?,?,?)').run(req.user.id,p.user_id,roomId,'g-end',JSON.stringify({username:req.user.username}));db.prepare('DELETE FROM call_room_members WHERE room_id=?').run(roomId);return res.json({ok:true,ended:true})}db.prepare('DELETE FROM call_room_members WHERE room_id=? AND user_id=?').run(roomId,req.user.id);for(const p of peers)db.prepare('INSERT INTO call_signals(from_id,to_id,call_id,type,payload) VALUES(?,?,?,?,?)').run(req.user.id,p.user_id,roomId,'g-leave',JSON.stringify({username:req.user.username}));res.json({ok:true,ended:false})});
app.get('/api/calls/signals',auth,(req,res)=>{const after=Number(req.query.after)||0;const rows=db.prepare("SELECT id,from_id,call_id,type,payload,created_at FROM call_signals WHERE to_id=? AND id>? AND created_at > datetime('now','-2 hours') AND (type NOT LIKE 'g-%' OR type='g-end' OR EXISTS(SELECT 1 FROM call_rooms r WHERE r.id=call_signals.call_id AND r.status='active')) ORDER BY id LIMIT 100").all(req.user.id,after);res.json({signals:rows.map(r=>({...r,payload:r.payload?JSON.parse(r.payload):null}))})});
app.post('/api/calls/signals',auth,(req,res)=>{const to=Number(req.body.to_id),callId=String(req.body.call_id||''),type=String(req.body.type||''),payload=req.body.payload??null;if(!to||to===req.user.id||!callId||callId.length>100||!['offer','answer','ice','hangup','reject','g-invite','g-peer-join','g-offer','g-answer','g-ice','g-leave','g-end'].includes(type))return res.status(400).json({error:'Некорректный сигнал звонка'});if(!db.prepare('SELECT id FROM users WHERE id=?').get(to))return res.status(404).json({error:'Пользователь не найден'});if(type.startsWith('g-')){const room=db.prepare("SELECT * FROM call_rooms WHERE id=? AND status='active'").get(callId);if(!room)return res.status(404).json({error:'Групповой звонок уже завершён'});if(!member(room.chat_id,req.user.id)||!member(room.chat_id,to))return res.status(403).json({error:'Для сигнализации звонка нужны права участника группы'});const senderJoined=!!db.prepare('SELECT 1 FROM call_room_members WHERE room_id=? AND user_id=?').get(callId,req.user.id);const targetJoined=!!db.prepare('SELECT 1 FROM call_room_members WHERE room_id=? AND user_id=?').get(callId,to);if(type==='g-invite'){if(room.host_id!==req.user.id||senderJoined!==true)return res.status(403).json({error:'Приглашать может только создатель звонка'})}else if(type==='g-peer-join'){if(!senderJoined||!targetJoined)return res.status(403).json({error:'Оба участника должны находиться в звонке'})}else if(!senderJoined||!targetJoined)return res.status(403).json({error:'Оба участника должны находиться в звонке'})}const r=db.prepare('INSERT INTO call_signals(from_id,to_id,call_id,type,payload) VALUES(?,?,?,?,?)').run(req.user.id,to,callId,type,payload===null?null:JSON.stringify(payload).slice(0,50000));res.json({ok:true,id:r.lastInsertRowid})});
app.use('/api',(req,res)=>res.status(404).json({error:'API-маршрут не найден',method:req.method,path:req.originalUrl,health:'/api/health'}));
app.use((req,res)=>res.status(404).json({error:'Страница не найдена',path:req.originalUrl,health:'/api/health'}));
app.use((err,req,res,next)=>{console.error('Unhandled server error:',err&&err.stack||err);if(res.headersSent)return next(err);const status=Number(err.status)||500;res.status(status>=400&&status<600?status:500).json({error:status===413?'Запрос слишком большой':status===400?'Некорректный запрос':'Внутренняя ошибка сервера',path:req.originalUrl})});
app.listen(PORT,'0.0.0.0',()=>console.log(`KESA server listening on ${PORT}`));
